name: Build & Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push api-gateway Image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ env.IMAGE_TAG }}

      - name: Build and Push vllm-server Image
        uses: docker/build-push-action@v5
        with:
          context: ./vllm-server
          file: ./vllm-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vllm-server:${{ env.IMAGE_TAG }}
